spring:
  application:
    name: eureka_client1
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ${APPLICATION_DOMAIN}
    non-secure-port: 80
    secure-port-enabled: true